version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.16.3
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run test
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - SUCCESS=$CODEBUILD_BUILD_SUCCEEDING node ./bin/notify.js
